spring:
  profiles:
    active: dev

---
server:
  port: 7071

spring:
  profiles: dev
  application:
    name: Eureka-Client
  datasource:
    url: jdbc:mysql://localhost:3306/user?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: admin


eureka:
  instance:
    instance-id: Eureka-Client1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka-server1.com:8081/eureka/,http://eureka-server2.com:8082/eureka/,http://eureka-server3.com:8083/eureka/
mybatis:
  type-aliases-package: com.example.eurekaclient1
  mapper-locations: classpath:mapper/*.xml