server:
  port: 8083

eureka:
  instance:
    hostname: eureka-server3.com
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka-server1.com:8081/eureka/,http://eureka-server2.com:8082/eureka/
